services:
  cmmc-tool:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      # Hot reload for development
      - .:/app
      - /app/node_modules
      - /app/.next
      # Data persistence volume
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - DATA_PATH=/app/data
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Production service (optional)
  cmmc-tool-prod:
    build:
      context: .
      target: runner
    ports:
      - "3001:3000"
    volumes:
      # Data persistence volume for production
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATA_PATH=/app/data
    restart: unless-stopped
    profiles:
      - production